//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUSS.SSM_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSM_Service.SSM_ServicesSoap")]
    public interface SSM_ServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/todto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.ToDTO todto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/monhocdto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.MonHocDTO monhocdto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lopdto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.LopDTO lopdto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hocsinhdto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.HocSinhDTO hocsinhdto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/giaoviendto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.GiaoVienDTO giaoviendto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kldto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.KhoiLopDTO kldto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/namhocdto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.NamHocDTO namhocdto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hkdto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        BUSS.SSM_Service.HocKyDTO hkdto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int To_Insert(BUSS.SSM_Service.ToDTO todto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int To_Update(BUSS.SSM_Service.ToDTO todto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int To_Delete(string mato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable To_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string To_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_searchbyMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable To_searchbyMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/To_SearchTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable To_SearchTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int MonHoc_Insert(BUSS.SSM_Service.MonHocDTO mh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int MonHoc_Update(BUSS.SSM_Service.MonHocDTO mh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable MonHoc_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int MonHoc_Delete(string mamon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_SearchbyMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable MonHoc_SearchbyMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_SeaerchbyTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable MonHoc_SeaerchbyTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string MonHoc_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int Lop_Insert(BUSS.SSM_Service.LopDTO lop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int Lop_Update(string malop, string tenlop, string magv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable Lop_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_Updatesiso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int Lop_Updatesiso(int siso, string malop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_searchbyMakl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable Lop_searchbyMakl(string makl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string Lop_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lop_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int Lop_Delete(string malop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KLop_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int KLop_Insert(BUSS.SSM_Service.KhoiLopDTO kl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KLop_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int KLop_Update(BUSS.SSM_Service.KhoiLopDTO kl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KLop_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable KLop_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KLop_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int KLop_Delete(string mkl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KLop_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string KLop_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamHoc_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int NamHoc_Insert(BUSS.SSM_Service.NamHocDTO nh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamHoc_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int NamHoc_Update(BUSS.SSM_Service.NamHocDTO nh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamHoc_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable NamHoc_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NamHoc_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string NamHoc_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocKy_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocKy_Insert(BUSS.SSM_Service.HocKyDTO hk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocKy_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocKy_Update(BUSS.SSM_Service.HocKyDTO hk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocKy_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocKy_Delete(string manam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocKy_searchbyMaNam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable HocKy_searchbyMaNam(string manam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocKy_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HocKy_getMa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocSinh_Insert(BUSS.SSM_Service.HocSinhDTO hs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocSinh_Update(BUSS.SSM_Service.HocSinhDTO hs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_Dekete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int HocSinh_Dekete(string mahs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_searchbyMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable HocSinh_searchbyMa(string mahs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_searchbyTen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable HocSinh_searchbyTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_SearchbyMa_FULL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable HocSinh_SearchbyMa_FULL(string mahs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HocSinh_getMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HocSinh_HSchuaphanlop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable HocSinh_HSchuaphanlop(string manam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GiaoVien_Insert(BUSS.SSM_Service.GiaoVienDTO gv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GiaoVien_Update(BUSS.SSM_Service.GiaoVienDTO gv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GiaoVien_Delete(string magv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_SearchbyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GiaoVien_SearchbyName(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_SearchbyMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GiaoVien_SearchbyMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_SearchbyMa_Full", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GiaoVien_SearchbyMa_Full(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GiaoVien_getMa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GiaoVien_getMa();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ToDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maToField;
        
        private string tenToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaTo {
            get {
                return this.maToField;
            }
            set {
                this.maToField = value;
                this.RaisePropertyChanged("MaTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenTo {
            get {
                return this.tenToField;
            }
            set {
                this.tenToField = value;
                this.RaisePropertyChanged("TenTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HocKyDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maHKField;
        
        private string ten_HocKyField;
        
        private string maNamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaHK {
            get {
                return this.maHKField;
            }
            set {
                this.maHKField = value;
                this.RaisePropertyChanged("MaHK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ten_HocKy {
            get {
                return this.ten_HocKyField;
            }
            set {
                this.ten_HocKyField = value;
                this.RaisePropertyChanged("Ten_HocKy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MaNam {
            get {
                return this.maNamField;
            }
            set {
                this.maNamField = value;
                this.RaisePropertyChanged("MaNam");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NamHocDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maNamField;
        
        private string ten_NamHocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaNam {
            get {
                return this.maNamField;
            }
            set {
                this.maNamField = value;
                this.RaisePropertyChanged("MaNam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ten_NamHoc {
            get {
                return this.ten_NamHocField;
            }
            set {
                this.ten_NamHocField = value;
                this.RaisePropertyChanged("Ten_NamHoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KhoiLopDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maKhoiLopField;
        
        private string tenKhoiLopField;
        
        private int soLopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaKhoiLop {
            get {
                return this.maKhoiLopField;
            }
            set {
                this.maKhoiLopField = value;
                this.RaisePropertyChanged("MaKhoiLop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenKhoiLop {
            get {
                return this.tenKhoiLopField;
            }
            set {
                this.tenKhoiLopField = value;
                this.RaisePropertyChanged("TenKhoiLop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SoLop {
            get {
                return this.soLopField;
            }
            set {
                this.soLopField = value;
                this.RaisePropertyChanged("SoLop");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GiaoVienDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maGVField;
        
        private string hoTenField;
        
        private int gioiTinhField;
        
        private string soDienThoaiField;
        
        private string chuyenNghanhField;
        
        private string trinhDoChuyenMonField;
        
        private string soTruongField;
        
        private string maToField;
        
        private string ngaySinhField;
        
        private string diaChiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaGV {
            get {
                return this.maGVField;
            }
            set {
                this.maGVField = value;
                this.RaisePropertyChanged("MaGV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
                this.RaisePropertyChanged("HoTen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
                this.RaisePropertyChanged("GioiTinh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
                this.RaisePropertyChanged("SoDienThoai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ChuyenNghanh {
            get {
                return this.chuyenNghanhField;
            }
            set {
                this.chuyenNghanhField = value;
                this.RaisePropertyChanged("ChuyenNghanh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TrinhDoChuyenMon {
            get {
                return this.trinhDoChuyenMonField;
            }
            set {
                this.trinhDoChuyenMonField = value;
                this.RaisePropertyChanged("TrinhDoChuyenMon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SoTruong {
            get {
                return this.soTruongField;
            }
            set {
                this.soTruongField = value;
                this.RaisePropertyChanged("SoTruong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MaTo {
            get {
                return this.maToField;
            }
            set {
                this.maToField = value;
                this.RaisePropertyChanged("MaTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
                this.RaisePropertyChanged("NgaySinh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
                this.RaisePropertyChanged("DiaChi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HocSinhDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maHSField;
        
        private string hoTenField;
        
        private int gioiTinhField;
        
        private string soDienThoaiField;
        
        private string hoTenChaField;
        
        private string ngheNghiepChaField;
        
        private string hoTenMeField;
        
        private string ngheNghiepMeField;
        
        private string ngaySinhField;
        
        private string diaChiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaHS {
            get {
                return this.maHSField;
            }
            set {
                this.maHSField = value;
                this.RaisePropertyChanged("MaHS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
                this.RaisePropertyChanged("HoTen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                this.gioiTinhField = value;
                this.RaisePropertyChanged("GioiTinh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
                this.RaisePropertyChanged("SoDienThoai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HoTenCha {
            get {
                return this.hoTenChaField;
            }
            set {
                this.hoTenChaField = value;
                this.RaisePropertyChanged("HoTenCha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NgheNghiepCha {
            get {
                return this.ngheNghiepChaField;
            }
            set {
                this.ngheNghiepChaField = value;
                this.RaisePropertyChanged("NgheNghiepCha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HoTenMe {
            get {
                return this.hoTenMeField;
            }
            set {
                this.hoTenMeField = value;
                this.RaisePropertyChanged("HoTenMe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NgheNghiepMe {
            get {
                return this.ngheNghiepMeField;
            }
            set {
                this.ngheNghiepMeField = value;
                this.RaisePropertyChanged("NgheNghiepMe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NgaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                this.ngaySinhField = value;
                this.RaisePropertyChanged("NgaySinh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DiaChi {
            get {
                return this.diaChiField;
            }
            set {
                this.diaChiField = value;
                this.RaisePropertyChanged("DiaChi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maLopField;
        
        private string tenLopField;
        
        private string maKhoiLopField;
        
        private string maGVCNField;
        
        private int siSoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaLop {
            get {
                return this.maLopField;
            }
            set {
                this.maLopField = value;
                this.RaisePropertyChanged("MaLop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenLop {
            get {
                return this.tenLopField;
            }
            set {
                this.tenLopField = value;
                this.RaisePropertyChanged("TenLop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MaKhoiLop {
            get {
                return this.maKhoiLopField;
            }
            set {
                this.maKhoiLopField = value;
                this.RaisePropertyChanged("MaKhoiLop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MaGVCN {
            get {
                return this.maGVCNField;
            }
            set {
                this.maGVCNField = value;
                this.RaisePropertyChanged("MaGVCN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SiSo {
            get {
                return this.siSoField;
            }
            set {
                this.siSoField = value;
                this.RaisePropertyChanged("SiSo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MonHocDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string maMonField;
        
        private string tenMonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MaMon {
            get {
                return this.maMonField;
            }
            set {
                this.maMonField = value;
                this.RaisePropertyChanged("MaMon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TenMon {
            get {
                return this.tenMonField;
            }
            set {
                this.tenMonField = value;
                this.RaisePropertyChanged("TenMon");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SSM_ServicesSoapChannel : BUSS.SSM_Service.SSM_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SSM_ServicesSoapClient : System.ServiceModel.ClientBase<BUSS.SSM_Service.SSM_ServicesSoap>, BUSS.SSM_Service.SSM_ServicesSoap {
        
        public SSM_ServicesSoapClient() {
        }
        
        public SSM_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSM_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSM_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSM_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BUSS.SSM_Service.ToDTO todto() {
            return base.Channel.todto();
        }
        
        public BUSS.SSM_Service.MonHocDTO monhocdto() {
            return base.Channel.monhocdto();
        }
        
        public BUSS.SSM_Service.LopDTO lopdto() {
            return base.Channel.lopdto();
        }
        
        public BUSS.SSM_Service.HocSinhDTO hocsinhdto() {
            return base.Channel.hocsinhdto();
        }
        
        public BUSS.SSM_Service.GiaoVienDTO giaoviendto() {
            return base.Channel.giaoviendto();
        }
        
        public BUSS.SSM_Service.KhoiLopDTO kldto() {
            return base.Channel.kldto();
        }
        
        public BUSS.SSM_Service.NamHocDTO namhocdto() {
            return base.Channel.namhocdto();
        }
        
        public BUSS.SSM_Service.HocKyDTO hkdto() {
            return base.Channel.hkdto();
        }
        
        public int To_Insert(BUSS.SSM_Service.ToDTO todto) {
            return base.Channel.To_Insert(todto);
        }
        
        public int To_Update(BUSS.SSM_Service.ToDTO todto) {
            return base.Channel.To_Update(todto);
        }
        
        public int To_Delete(string mato) {
            return base.Channel.To_Delete(mato);
        }
        
        public System.Data.DataTable To_List() {
            return base.Channel.To_List();
        }
        
        public string To_getMa() {
            return base.Channel.To_getMa();
        }
        
        public System.Data.DataTable To_searchbyMa(string ma) {
            return base.Channel.To_searchbyMa(ma);
        }
        
        public System.Data.DataTable To_SearchTen(string ten) {
            return base.Channel.To_SearchTen(ten);
        }
        
        public int MonHoc_Insert(BUSS.SSM_Service.MonHocDTO mh) {
            return base.Channel.MonHoc_Insert(mh);
        }
        
        public int MonHoc_Update(BUSS.SSM_Service.MonHocDTO mh) {
            return base.Channel.MonHoc_Update(mh);
        }
        
        public System.Data.DataTable MonHoc_List() {
            return base.Channel.MonHoc_List();
        }
        
        public int MonHoc_Delete(string mamon) {
            return base.Channel.MonHoc_Delete(mamon);
        }
        
        public System.Data.DataTable MonHoc_SearchbyMa(string ma) {
            return base.Channel.MonHoc_SearchbyMa(ma);
        }
        
        public System.Data.DataTable MonHoc_SeaerchbyTen(string ten) {
            return base.Channel.MonHoc_SeaerchbyTen(ten);
        }
        
        public string MonHoc_getMa() {
            return base.Channel.MonHoc_getMa();
        }
        
        public int Lop_Insert(BUSS.SSM_Service.LopDTO lop) {
            return base.Channel.Lop_Insert(lop);
        }
        
        public int Lop_Update(string malop, string tenlop, string magv) {
            return base.Channel.Lop_Update(malop, tenlop, magv);
        }
        
        public System.Data.DataTable Lop_List() {
            return base.Channel.Lop_List();
        }
        
        public int Lop_Updatesiso(int siso, string malop) {
            return base.Channel.Lop_Updatesiso(siso, malop);
        }
        
        public System.Data.DataTable Lop_searchbyMakl(string makl) {
            return base.Channel.Lop_searchbyMakl(makl);
        }
        
        public string Lop_getMa() {
            return base.Channel.Lop_getMa();
        }
        
        public int Lop_Delete(string malop) {
            return base.Channel.Lop_Delete(malop);
        }
        
        public int KLop_Insert(BUSS.SSM_Service.KhoiLopDTO kl) {
            return base.Channel.KLop_Insert(kl);
        }
        
        public int KLop_Update(BUSS.SSM_Service.KhoiLopDTO kl) {
            return base.Channel.KLop_Update(kl);
        }
        
        public System.Data.DataTable KLop_List() {
            return base.Channel.KLop_List();
        }
        
        public int KLop_Delete(string mkl) {
            return base.Channel.KLop_Delete(mkl);
        }
        
        public string KLop_getMa() {
            return base.Channel.KLop_getMa();
        }
        
        public int NamHoc_Insert(BUSS.SSM_Service.NamHocDTO nh) {
            return base.Channel.NamHoc_Insert(nh);
        }
        
        public int NamHoc_Update(BUSS.SSM_Service.NamHocDTO nh) {
            return base.Channel.NamHoc_Update(nh);
        }
        
        public System.Data.DataTable NamHoc_List() {
            return base.Channel.NamHoc_List();
        }
        
        public string NamHoc_getMa() {
            return base.Channel.NamHoc_getMa();
        }
        
        public int HocKy_Insert(BUSS.SSM_Service.HocKyDTO hk) {
            return base.Channel.HocKy_Insert(hk);
        }
        
        public int HocKy_Update(BUSS.SSM_Service.HocKyDTO hk) {
            return base.Channel.HocKy_Update(hk);
        }
        
        public int HocKy_Delete(string manam) {
            return base.Channel.HocKy_Delete(manam);
        }
        
        public System.Data.DataTable HocKy_searchbyMaNam(string manam) {
            return base.Channel.HocKy_searchbyMaNam(manam);
        }
        
        public string HocKy_getMa() {
            return base.Channel.HocKy_getMa();
        }
        
        public int HocSinh_Insert(BUSS.SSM_Service.HocSinhDTO hs) {
            return base.Channel.HocSinh_Insert(hs);
        }
        
        public int HocSinh_Update(BUSS.SSM_Service.HocSinhDTO hs) {
            return base.Channel.HocSinh_Update(hs);
        }
        
        public int HocSinh_Dekete(string mahs) {
            return base.Channel.HocSinh_Dekete(mahs);
        }
        
        public System.Data.DataTable HocSinh_searchbyMa(string mahs) {
            return base.Channel.HocSinh_searchbyMa(mahs);
        }
        
        public System.Data.DataTable HocSinh_searchbyTen(string ten) {
            return base.Channel.HocSinh_searchbyTen(ten);
        }
        
        public System.Data.DataTable HocSinh_SearchbyMa_FULL(string mahs) {
            return base.Channel.HocSinh_SearchbyMa_FULL(mahs);
        }
        
        public string HocSinh_getMa(string ma) {
            return base.Channel.HocSinh_getMa(ma);
        }
        
        public System.Data.DataTable HocSinh_HSchuaphanlop(string manam) {
            return base.Channel.HocSinh_HSchuaphanlop(manam);
        }
        
        public int GiaoVien_Insert(BUSS.SSM_Service.GiaoVienDTO gv) {
            return base.Channel.GiaoVien_Insert(gv);
        }
        
        public int GiaoVien_Update(BUSS.SSM_Service.GiaoVienDTO gv) {
            return base.Channel.GiaoVien_Update(gv);
        }
        
        public int GiaoVien_Delete(string magv) {
            return base.Channel.GiaoVien_Delete(magv);
        }
        
        public System.Data.DataTable GiaoVien_SearchbyName(string ten) {
            return base.Channel.GiaoVien_SearchbyName(ten);
        }
        
        public System.Data.DataTable GiaoVien_SearchbyMa(string ma) {
            return base.Channel.GiaoVien_SearchbyMa(ma);
        }
        
        public System.Data.DataTable GiaoVien_SearchbyMa_Full(string ma) {
            return base.Channel.GiaoVien_SearchbyMa_Full(ma);
        }
        
        public string GiaoVien_getMa() {
            return base.Channel.GiaoVien_getMa();
        }
    }
}
